services:
  x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./db:/etc/x-ui
      - /root/cert/:/root/cert
    ports:
      - "9053:2053"
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
      - "9096:9096"
    restart: unless-stopped
