services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - /root/3x-ui/db:/etc/x-ui
      - /root/cert/:/root/cert
    ports:
      - "9053:2053"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"
      - "9006:9006"
    restart: unless-stopped
