services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9080:80"
      - "443:443"
    volumes:
      - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/conf/conf.d:/etc/nginx/conf.d
      - /root/nginx/log:/var/log/nginx
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/static:/usr/share/nginx/static
      - /root/cert:/usr/share/nginx/cert
    restart: always
